# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y930LLCGpXjib3v33AcDzmrT8DWle4Ht
"""

!pip install streamlit

import streamlit as st
import pickle

from google.colab import drive
drive.mount('/content/drive')

model_path = '/content/drive/MyDrive/Final_Project_ML/multinomial_nb_model.pkl'
vectorizer_path = '/content/drive/MyDrive/Final_Project_ML/tfidf_vectorizer.pkl'

with open(model_path, 'rb') as f:
    model = pickle.load(f)

with open(vectorizer_path, 'rb') as f:
    vectorizer = pickle.load(f)

st.set_page_config(page_title="Deteksi Berita Hoaks", layout="centered")
st.title("📰 Deteksi Berita Hoaks Bahasa Indonesia")
st.markdown("Masukkan **judul** dan **isi berita**, lalu klik tombol **Deteksi** untuk mengetahui apakah berita itu **HOAKS (1)** atau **VALID (0)**.")

judul = st.text_input("📝 Judul Berita")
isi = st.text_area("📄 Isi Berita")

if st.button("🔍 Deteksi"):
    if judul and isi:
        full_text = judul + " " + isi
        X_input = vectorizer.transform([full_text])
        prediction = model.predict(X_input)[0]
        proba = model.predict_proba(X_input)[0][prediction]

        if prediction == 1:
            st.error(f"🚨 Deteksi: **HOAKS** (Probabilitas: {proba:.2f})")
        else:
            st.success(f"✅ Deteksi: **VALID** (Probabilitas: {proba:.2f})")
    else:
        st.warning("⚠️ Harap isi semua kolom terlebih dahulu.")

