# -*- coding: utf-8 -*-
"""Train_Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OElJNqI-XNz_kx3AnPYC1wGEjmJnHEuj
"""

!pip install sastrawi

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import pickle
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

df = pd.read_csv('/content/drive/MyDrive/Final_Project_ML/Scrapping.csv', encoding='ISO-8859-1', engine='python', on_bad_lines='warn', delimiter=';')

df['text'] = df['Headline'].astype(str) + " " + df['Body'].astype(str)

X = df['text']
y = df['Label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

factory = StopWordRemoverFactory()
indonesian_stop_words = factory.get_stop_words()

vectorizer = TfidfVectorizer(stop_words=indonesian_stop_words, max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train)

model = MultinomialNB()
model.fit(X_train_vec, y_train)

model_path = '/content/drive/MyDrive/Final_Project_ML/multinomial_nb_model.pkl'
vectorizer_path = '/content/drive/MyDrive/Final_Project_ML/tfidf_vectorizer.pkl'

with open(model_path, 'wb') as f:
    pickle.dump(model, f)

with open(vectorizer_path, 'wb') as f:
    pickle.dump(vectorizer, f)

print("✅ Model dan vectorizer berhasil disimpan ke Google Drive.")

